src/__init__.py
from decouple import config as decouple_config
from flask import Flask, Response
import logging
from logging import StreamHandler
from flask_wtf.csrf import CSRFProtect
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from dotenv import load_dotenv
from src.utils.is_active_utils import is_active
from src.utils.mask_password_utils import mask_password
from src.config import DevelopmentConfig, TestingConfig, ProductionConfig, get_uuid_type
from flask_mail import Mail
from flask_talisman import Talisman
import openai
import os
from flask_marshmallow import Marshmallow
from flask_jwt_extended import JWTManager

# Load .env file variable
load_dotenv()

# Initialize extensions
bcrypt = Bcrypt()
db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
csrf = CSRFProtect()
mail = Mail()
ma = Marshmallow()
jwt = JWTManager()

# Global variable for UUID type
UUID_TYPE = None


def create_app(config_class=None):
    global UUID_TYPE

    app = Flask(__name__)

    # Membaca konfigurasi dari file .env
    config_name = decouple_config("CONFIG_NAME", default="Development")

    # Memilih konfigurasi berdasarkan nama
    if config_name == "Development":
        app.config.from_object(DevelopmentConfig)
    elif config_name == "Testing":
        app.config.from_object(TestingConfig)
    elif config_name == "Production":
        app.config.from_object(ProductionConfig)
    else:
        raise ValueError("Invalid CONFIG_NAME")

    # Pastikan semua direktori yang dibutuhkan ada
    for directory in [
        app.config["BACKUP_DIR"],
        app.config["CONFIG_DIR"],
        app.config["TEMPLATE_DIR"],
    ]:
        try:
            if not os.path.exists(directory):
                os.makedirs(directory)
                app.logger.info(f"Created missing directory: {directory}")
            else:
                app.logger.info(f"Directory already exists: {directory}")
        except OSError as e:
            app.logger.error(f"Error creating directory {directory}: {e}")
            raise RuntimeError(f"Failed to create directory: {directory}")

    # Inisiasi pustaka OpenAI dengan API key
    openai_api_key = decouple_config("OPENAI_API_KEY", default=None)
    talita_api_key = decouple_config("TALITA_API_KEY", default=None)
    talita_url = decouple_config("TALITA_URL", default=None)

    # JWT Secret Key
    jwt_secret_key = decouple_config("JWT_SECRET_KEY", default=None)

    # Pengecekan apakah variabel konfigurasi penting telah dimuat
    if not openai_api_key:
        raise ValueError("Missing required configuration: OPENAI_API_KEY")
    if not talita_api_key:
        raise ValueError("Missing required configuration: TALITA_API_KEY")
    if not talita_url:
        raise ValueError("Missing required configuration: TALITA_URL")

    # Set API key untuk OpenAI
    openai.api_key = openai_api_key

    # Simpan TALITA API Key dan URL ke dalam konfigurasi aplikasi
    app.config["TALITA_API_KEY"] = talita_api_key
    app.config["TALITA_URL"] = talita_url

    # set config for JWT Extended Library
    app.config["JWT_SECRET_KEY"] = jwt_secret_key
    app.config["JWT_ACCESS_TOKEN_EXPIRES"] = (
        False  # Token akses tidak pernah kedaluwarsa
    )
    app.config["JWT_REFRESH_TOKEN_EXPIRES"] = (
        False  # Token refresh juga tidak pernah kedaluwarsa
    )

    # Initialize extensions
    bcrypt.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    csrf.init_app(app)
    mail.init_app(app)
    ma.init_app(app)
    jwt.init_app(app)
    talisman = Talisman(
        app,
        force_https=app.config["TALISMAN_FORCE_HTTPS"],
        strict_transport_security=app.config["TALISMAN_STRICT_TRANSPORT_SECURITY"],
        strict_transport_security_max_age=app.config[
            "TALISMAN_STRICT_TRANSPORT_SECURITY_MAX_AGE"
        ],
        content_security_policy=app.config["TALISMAN_CONTENT_SECURITY_POLICY"],
    )

    # Set UUID type based on database type
    UUID_TYPE = get_uuid_type(app.config["SQLALCHEMY_DATABASE_URI"])

    # Konfigurasi logger
    handler = StreamHandler()
    handler.setLevel(logging.INFO)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    handler.setFormatter(formatter)

    app.logger.addHandler(handler)
    app.logger.setLevel(logging.INFO)

    # Register context processor
    app.jinja_env.filters["mask_password"] = mask_password

    # Middleware to modify the Server header
    @app.after_request
    def hide_server_header(response: Response):
        # Change the Server header or remove it completely
        response.headers["Server"] = "Hidden Server"
        return response

    @app.context_processor
    def utility_processor():
        return dict(is_active=is_active)

    # Register blueprints
    from .controllers.main_controller import main_bp
    from .controllers.users_controller import users_bp
    from .controllers.profile_controller import profile_bp
    from .controllers.roles_controller import roles_bp
    from .controllers.device_manager_controller import dm_bp
    from .controllers.template_manager_controller import tm_bp
    from .controllers.config_manager_controller import nm_bp
    from .utils.error_helper_utils import error_bp
    from .controllers.backup_controller import backup_bp
    from .controllers.ai_chatbot_controller import chatbot_bp
    from .controllers.config_file_manager_controller import config_file_bp
    from .controllers.restfull_api_controller import restapi_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(users_bp)
    app.register_blueprint(profile_bp)
    app.register_blueprint(roles_bp)
    app.register_blueprint(dm_bp)
    app.register_blueprint(tm_bp)
    app.register_blueprint(nm_bp)
    app.register_blueprint(error_bp)
    app.register_blueprint(backup_bp)
    app.register_blueprint(chatbot_bp)
    app.register_blueprint(config_file_bp)
    app.register_blueprint(restapi_bp)

    # Set up user loader
    from .models.app_models import User

    login_manager.login_view = "main.login"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == user_id).first()

    return app

src/controllers/template_manager_controller.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    current_app,
    jsonify,
)
from flask_login import login_required, current_user, logout_user
from src import db
from src.models.app_models import TemplateManager, ConfigurationManager
from src.utils.config_manager_utils import ConfigurationManagerUtils
from src.utils.openai_utils import (
    validate_generated_template_with_openai,
)
from werkzeug.utils import secure_filename
import os
from datetime import datetime
from .decorators import login_required, role_required, required_2fa
import random
import string
from flask_paginate import Pagination, get_page_args
import logging
from src.utils.forms_utils import (
    TemplateForm,
    TemplateUpdateForm,
    ManualTemplateForm,
)

# Blueprint untuk template manager
tm_bp = Blueprint("tm", __name__)
error_bp = Blueprint("error", __name__)

# Setup logging untuk aplikasi
logging.basicConfig(level=logging.INFO)


@tm_bp.before_app_request
def setup_logging():
    """
    Mengatur level logging untuk aplikasi.
    """
    current_app.logger.setLevel(logging.INFO)
    handler = current_app.logger.handlers[0]
    current_app.logger.addHandler(handler)


@error_bp.app_errorhandler(404)
def page_not_found(error):
    """
    Menangani error 404 dan menampilkan halaman 404.
    """
    current_app.logger.error(f"Error 404: {error}")
    return render_template("main/404.html"), 404


# Middleware untuk autentikasi dan otorisasi sebelum permintaan.
@tm_bp.before_request
def before_request_func():
    """
    Memeriksa apakah pengguna telah terotentikasi sebelum setiap permintaan.
    Jika pengguna harus logout paksa, lakukan logout dan arahkan ke halaman login.
    Jika tidak terotentikasi, kembalikan pesan 'Unauthorized access'.
    """
    if not current_user.is_authenticated:
        current_app.logger.warning(
            f"Unauthorized access attempt by {request.remote_addr}"
        )
        return render_template("main/404.html"), 404

    # Jika pengguna terotentikasi dan memiliki flag force_logout, lakukan logout
    if current_user.force_logout:
        current_user.force_logout = False  # Reset the flag
        db.session.commit()
        logout_user()
        flash("Your password has been updated. Please log in again.", "info")
        return redirect(url_for("main.login"))


@tm_bp.context_processor
def inject_user():
    """
    Menyediakan first_name dan last_name pengguna yang terotentikasi ke dalam template.
    """
    if current_user.is_authenticated:
        return dict(
            first_name=current_user.first_name, last_name=current_user.last_name
        )
    return dict(first_name="", last_name="")


# --------------------------------------------------------------------------------
# Bagian Template Management
# --------------------------------------------------------------------------------


def allowed_file(filename, allowed_extensions):
    """Memeriksa apakah ekstensi file termasuk dalam ekstensi yang diperbolehkan."""
    return "." in filename and filename.rsplit(".", 1)[1].lower() in allowed_extensions


def save_uploaded_file(file, upload_folder):
    filename = secure_filename(file.filename)
    file_path = os.path.join(current_app.static_folder, upload_folder, filename)
    file.save(file_path)
    current_app.logger.info(f"File uploaded: {filename}")
    return filename


def read_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as file:
            return file.read()
    except FileNotFoundError:
        current_app.logger.error(f"File not found: {filepath}")
        return None
    except Exception as e:
        current_app.logger.error(f"Error reading file {filepath}: {e}")
        return None


def generate_random_filename(vendor_name):
    random_str = "".join(random.choices(string.ascii_letters + string.digits, k=8))
    date_str = datetime.now().strftime("%d_%m_%Y")
    filename = f"{vendor_name}_{random_str}_{date_str}"
    current_app.logger.info(f"Generated random filename: {filename}")
    return filename


RAW_TEMPLATE_FOLDER = "xmanager/templates"
GEN_TEMPLATE_FOLDER = "xmanager/configurations"
TEMPLATE_EXTENSIONS = {"j2"}
PARAMS_EXTENSIONS = {"yml", "yaml"}


@tm_bp.route("/templates-management", methods=["GET"])
@login_required
@required_2fa
@role_required(
    roles=["Admin", "User", "View"],
    permissions=["Manage Templates", "View Templates"],
    page="Templates Management",
)
def index():
    """
    Display the main page of the Templates File Manager.
    This page includes a list of Templates file and supports pagination and searching.
    """
    # Logging untuk akses ke endpoint
    current_app.logger.info(f"{current_user.email} accessed index template management")

    form = TemplateForm(request.form)
    form_manual_create = ManualTemplateForm(request.form)

    search_query = request.args.get("search", "").lower()
    page, per_page, offset = get_page_args(
        page_parameter="page", per_page_parameter="per_page", per_page=10
    )
    if page < 1 or per_page < 1:
        raise ValueError("Page and per_page must be positive integers.")

    try:
        # Inisialisasi query default agar selalu ada nilai
        query = TemplateManager.query

        if search_query:
            query = query.filter(
                TemplateManager.template_name.ilike(f"%{search_query}%")
                | TemplateManager.parameter_name.ilike(f"%{search_query}%")
                | TemplateManager.vendor.ilike(f"%{search_query}%")
                | TemplateManager.version.ilike(f"%{search_query}%")
            )

        total_templates = query.count()
        templates = query.limit(per_page).offset(offset).all()
        pagination = Pagination(page=page, per_page=per_page, total=total_templates)

        # Logging jika tidak ada hasil pencarian
        if total_templates == 0:
            current_app.logger.info(
                f"No template file found for user {current_user.email} with query '{search_query}'"
            )
            flash("No template found matching your search criteria.", "info")

        return render_template(
            "/template_managers/index.html",
            form=form,
            form_manual_create=form_manual_create,
            page=page,
            per_page=per_page,
            search_query=search_query,
            total_templates=total_templates,
            templates=templates,
            pagination=pagination,
        )
    except Exception as e:
        # Handle any unexpected errors that occur during the query or pagination
        current_app.logger.error(f"Error accessing Template Manager page: {str(e)}")
        flash(
            "Terjadi kesalahan saat mengakses template. Silakan coba lagi nanti.",
            "danger",
        )
        return redirect(
            url_for("users.dashboard")
        )  # Redirect to a safe page like dashboard


@tm_bp.route("/template_detail/<template_id>", methods=["GET"])
@login_required
@required_2fa
@role_required(
    roles=["Admin", "User", "View"],
    permissions=["Manage Templates", "View Templates"],
    page="Templates Management",
)
def template_detail(template_id):
    template = TemplateManager.query.get_or_404(template_id)
    try:
        # Ensure paths are safe
        template_file_path = os.path.join(
            current_app.static_folder, RAW_TEMPLATE_FOLDER, template.template_name
        )
        parameter_file_path = os.path.join(
            current_app.static_folder, RAW_TEMPLATE_FOLDER, template.parameter_name
        )

        # Reading template and parameter files
        if not os.path.isfile(template_file_path) or not os.path.isfile(
            parameter_file_path
        ):
            current_app.logger.error(
                f"Template or parameter file not found for template ID {template_id} accessed by {current_user.email}"
            )
            return (
                jsonify({"error": "Template atau parameter file tidak ditemukan."}),
                404,
            )

        template_content = read_file(template_file_path)
        parameter_content = read_file(parameter_file_path)

        if template_content is None or parameter_content is None:
            current_app.logger.error(
                f"Error reading files for template ID {template_id} by {current_user.email}"
            )
            return (
                jsonify(
                    {
                        "error": "Terjadi kesalahan saat membaca konten template atau parameter."
                    }
                ),
                500,
            )

        current_app.logger.info(
            f"User {current_user.email} accessed details for template ID {template_id}"
        )
        return jsonify(
            {
                "template_name": template.template_name,
                "parameter_name": template.parameter_name,
                "vendor": template.vendor,
                "version": template.version,
                "description": template.description,
                "template_content": template_content,
                "parameter_content": parameter_content,
                "created_by": template.created_by,
            }
        )

    except Exception as e:
        current_app.logger.error(
            f"Unexpected error in template_detail for template ID {template_id} by {current_user.email}: {str(e)}"
        )
        return (
            jsonify(
                {
                    "error": "Terjadi kesalahan yang tidak terduga. Silakan coba lagi nanti."
                }
            ),
            500,
        )


@tm_bp.route("/upload-template", methods=["POST"])
@login_required
@required_2fa
@role_required(
    roles=["Admin", "User"],
    permissions=["Manage Templates"],
    page="Templates Management",
)
def upload_template():

src/templates/template_managers/update_template.html
{% extends "/layouts/layout.html" %}
{% block title %}Update Template{% endblock %}
{% block content %}
<!-- Page Content for Updating Template -->
<div class="card position-relative py-4 px-4">
    <div class="card-header mb-3">
        Update Template
    </div>
    <form action="{{ url_for('tm.update_template', template_id=template.id) }}" method="post" class="needs-validation"
        novalidate>
        {{ form.hidden_tag() }}

        <div class="row mb-3">
            <div class="col-md-6">
                <label for="template_name" class="form-label">Template Name</label>
                {{ form.template_name(class="form-control", id="template_name") }}
                {% if form.template_name.errors %}
                {% for error in form.template_name.errors %}
                <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="col-md-6">
                <label for="parameter_name" class="form-label">Parameter Name</label>
                {{ form.parameter_name(class="form-control", id="parameter_name") }}
                {% if form.parameter_name.errors %}
                {% for error in form.parameter_name.errors %}
                <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                <label for="vendor" class="form-label">Vendor</label>
                {{ form.vendor(class="form-control", id="vendor") }}
                {% if form.vendor.errors %}
                {% for error in form.vendor.errors %}
                <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="col-md-6">
                <label for="version" class="form-label">Version</label>
                {{ form.version(class="form-control", id="version") }}
                {% if form.version.errors %}
                {% for error in form.version.errors %}
                <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            {{ form.description(class="form-control", id="description") }}
            {% if form.description.errors %}
            {% for error in form.description.errors %}
            <div class="invalid-feedback d-block">{{ error }}</div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="template_content" class="form-label">Template Content</label>
            {{ form.template_content(class="form-control", id="template_content", rows="5") }}
            {% if form.template_content.errors %}
            {% for error in form.template_content.errors %}
            <div class="invalid-feedback d-block">{{ error }}</div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="parameter_content" class="form-label">Parameter Content</label>
            {{ form.parameter_content(class="form-control", id="parameter_content", rows="5") }}
            {% if form.parameter_content.errors %}
            {% for error in form.parameter_content.errors %}
            <div class="invalid-feedback d-block">{{ error }}</div>
            {% endfor %}
            {% endif %}
        </div>

        <!-- Tombol Aksi -->
        <button type="submit" class="btn btn-sm btn-success">
            <i class="fa-solid fa-check"></i> Save Changes
        </button>
        <a class="btn btn-sm btn-warning" href="{{ url_for('tm.index') }}">
            <i class="fa-solid fa-arrow-left"></i> Back
        </a>
    </form>
</div>

{% block script_js %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Bootstrap validation script
        var forms = document.querySelectorAll('.needs-validation');
        Array.prototype.slice.call(forms).forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                    event.preventDefault();
                    event.stopPropagation();
                }
                form.classList.add('was-validated');
            }, false);
        });
    });
</script>
{% endblock %}
{% endblock %}