src/__init__.py
from decouple import config as decouple_config
from flask import Flask, Response
import logging
from logging import StreamHandler
from flask_wtf.csrf import CSRFProtect
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from dotenv import load_dotenv
from src.utils.is_active_utils import is_active
from src.utils.mask_password_utils import mask_password
from src.config import DevelopmentConfig, TestingConfig, ProductionConfig, get_uuid_type
from flask_mail import Mail
from flask_talisman import Talisman
import openai
import os
from flask_marshmallow import Marshmallow
from flask_jwt_extended import JWTManager

# Load .env file variable
load_dotenv()

# Initialize extensions
bcrypt = Bcrypt()
db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
csrf = CSRFProtect()
mail = Mail()
ma = Marshmallow()
jwt = JWTManager()

# Global variable for UUID type
UUID_TYPE = None


def create_app(config_class=None):
    global UUID_TYPE

    app = Flask(__name__)

    # Membaca konfigurasi dari file .env
    config_name = decouple_config("CONFIG_NAME", default="Development")

    # Memilih konfigurasi berdasarkan nama
    if config_name == "Development":
        app.config.from_object(DevelopmentConfig)
    elif config_name == "Testing":
        app.config.from_object(TestingConfig)
    elif config_name == "Production":
        app.config.from_object(ProductionConfig)
    else:
        raise ValueError("Invalid CONFIG_NAME")

    # Pastikan semua direktori yang dibutuhkan ada
    for directory in [
        app.config["BACKUP_DIR"],
        app.config["CONFIG_DIR"],
        app.config["TEMPLATE_DIR"],
    ]:
        try:
            if not os.path.exists(directory):
                os.makedirs(directory)
                app.logger.info(f"Created missing directory: {directory}")
            else:
                app.logger.info(f"Directory already exists: {directory}")
        except OSError as e:
            app.logger.error(f"Error creating directory {directory}: {e}")
            raise RuntimeError(f"Failed to create directory: {directory}")

    # Inisiasi pustaka OpenAI dengan API key
    openai_api_key = decouple_config("OPENAI_API_KEY", default=None)
    talita_api_key = decouple_config("TALITA_API_KEY", default=None)
    talita_url = decouple_config("TALITA_URL", default=None)

    # JWT Secret Key
    jwt_secret_key = decouple_config("JWT_SECRET_KEY", default=None)

    # Pengecekan apakah variabel konfigurasi penting telah dimuat
    if not openai_api_key:
        raise ValueError("Missing required configuration: OPENAI_API_KEY")
    if not talita_api_key:
        raise ValueError("Missing required configuration: TALITA_API_KEY")
    if not talita_url:
        raise ValueError("Missing required configuration: TALITA_URL")

    # Set API key untuk OpenAI
    openai.api_key = openai_api_key

    # Simpan TALITA API Key dan URL ke dalam konfigurasi aplikasi
    app.config["TALITA_API_KEY"] = talita_api_key
    app.config["TALITA_URL"] = talita_url

    # set config for JWT Extended Library
    app.config["JWT_SECRET_KEY"] = jwt_secret_key
    app.config["JWT_ACCESS_TOKEN_EXPIRES"] = (
        False  # Token akses tidak pernah kedaluwarsa
    )
    app.config["JWT_REFRESH_TOKEN_EXPIRES"] = (
        False  # Token refresh juga tidak pernah kedaluwarsa
    )

    # Initialize extensions
    bcrypt.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    csrf.init_app(app)
    mail.init_app(app)
    ma.init_app(app)
    jwt.init_app(app)
    talisman = Talisman(
        app,
        force_https=app.config["TALISMAN_FORCE_HTTPS"],
        strict_transport_security=app.config["TALISMAN_STRICT_TRANSPORT_SECURITY"],
        strict_transport_security_max_age=app.config[
            "TALISMAN_STRICT_TRANSPORT_SECURITY_MAX_AGE"
        ],
        content_security_policy=app.config["TALISMAN_CONTENT_SECURITY_POLICY"],
    )

    # Set UUID type based on database type
    UUID_TYPE = get_uuid_type(app.config["SQLALCHEMY_DATABASE_URI"])

    # Konfigurasi logger
    handler = StreamHandler()
    handler.setLevel(logging.INFO)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    handler.setFormatter(formatter)

    app.logger.addHandler(handler)
    app.logger.setLevel(logging.INFO)

    # Register context processor
    app.jinja_env.filters["mask_password"] = mask_password

    # Middleware to modify the Server header
    @app.after_request
    def hide_server_header(response: Response):
        # Change the Server header or remove it completely
        response.headers["Server"] = "Hidden Server"
        return response

    @app.context_processor
    def utility_processor():
        return dict(is_active=is_active)

    # Register blueprints
    from .controllers.main_controller import main_bp
    from .controllers.users_controller import users_bp
    from .controllers.profile_controller import profile_bp
    from .controllers.roles_controller import roles_bp
    from .controllers.device_manager_controller import dm_bp
    from .controllers.template_manager_controller import tm_bp
    from .controllers.config_manager_controller import nm_bp
    from .utils.error_helper_utils import error_bp
    from .controllers.backup_controller import backup_bp
    from .controllers.ai_chatbot_controller import chatbot_bp
    from .controllers.config_file_manager_controller import config_file_bp
    from .controllers.restfull_api_controller import restapi_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(users_bp)
    app.register_blueprint(profile_bp)
    app.register_blueprint(roles_bp)
    app.register_blueprint(dm_bp)
    app.register_blueprint(tm_bp)
    app.register_blueprint(nm_bp)
    app.register_blueprint(error_bp)
    app.register_blueprint(backup_bp)
    app.register_blueprint(chatbot_bp)
    app.register_blueprint(config_file_bp)
    app.register_blueprint(restapi_bp)

    # Set up user loader
    from .models.app_models import User

    login_manager.login_view = "main.login"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == user_id).first()

    return app

src/controllers/device_manager_controller.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
    current_app,
)
from flask_login import login_required, current_user, logout_user
from src import db
from src.models.app_models import DeviceManager
from .decorators import login_required, role_required, required_2fa
from src.utils.forms_utils import DeviceForm, DeviceUpdateForm
from flask_paginate import Pagination, get_page_args
import logging

# Create blueprints for the device manager (dm_bp) and error handling (error_bp)
dm_bp = Blueprint("dm", __name__)
error_bp = Blueprint("error", __name__)

# Setup logging configuration for the application
logging.basicConfig(level=logging.INFO)


@dm_bp.before_app_request
def setup_logging():
    """
    Configure logging for the application.
    This function ensures that all logs are captured at the INFO level,
    making it easier to track the flow of the application and debug issues.
    """
    current_app.logger.setLevel(logging.INFO)
    handler = current_app.logger.handlers[0]  # Use the first handler
    current_app.logger.addHandler(handler)


@error_bp.app_errorhandler(404)
def page_not_found(error):
    """
    Handle 404 errors and display a custom 404 error page.
    Logs the occurrence of a 404 error, which indicates a page was not found.
    """
    current_app.logger.error(f"Error 404: {error}")  # Log the error for debugging
    return render_template("main/404.html"), 404  # Render the custom 404 page


# Middleware untuk autentikasi dan otorisasi sebelum permintaan.
@dm_bp.before_request
def before_request_func():
    """
    Memeriksa apakah pengguna telah terotentikasi sebelum setiap permintaan.
    Jika pengguna harus logout paksa, lakukan logout dan arahkan ke halaman login.
    Jika tidak terotentikasi, kembalikan pesan 'Unauthorized access'.
    """
    if not current_user.is_authenticated:
        current_app.logger.warning(
            f"Unauthorized access attempt by {request.remote_addr}"
        )
        return render_template("main/404.html"), 404

    # Jika pengguna terotentikasi dan memiliki flag force_logout, lakukan logout
    if current_user.force_logout:
        current_user.force_logout = False  # Reset the flag
        db.session.commit()
        logout_user()
        flash("Your password has been updated. Please log in again.", "info")
        return redirect(url_for("main.login"))


@dm_bp.context_processor
def inject_user():
    """
    Provide the authenticated user's first name and last name to the template context.
    This allows templates to access user information for personalized greetings or other user-specific content.
    """
    if current_user.is_authenticated:
        return dict(
            first_name=current_user.first_name, last_name=current_user.last_name
        )
    return dict(
        first_name="", last_name=""
    )  # Return empty strings if the user is not authenticated


# -----------------------------------------------------------
# Devices Manager Section
# -----------------------------------------------------------


@dm_bp.route("/devices-management", methods=["GET"])
@login_required  # Ensure the user is logged in
@required_2fa  # Require two-factor authentication for added security
@role_required(
    roles=["Admin", "User", "View"],  # Restrict access based on user roles
    permissions=[
        "Manage Devices",
        "View Devices",
    ],  # Further restrict access based on permissions
    page="Devices Management",  # Indicate the page for role management
)
def index():
    """
    Display the main page of the Device Manager.
    This page includes a list of devices and supports pagination and searching.
    """
    # Logging untuk akses ke endpoint
    current_app.logger.info(f"{current_user.email} accessed index_configuration_file")

    form = DeviceForm(request.form)

    search_query = request.args.get("search", "").lower()
    page, per_page, offset = get_page_args(
        page_parameter="page", per_page_parameter="per_page", per_page=10
    )
    if page < 1 or per_page < 1:
        raise ValueError("Page and per_page must be positive integers.")

    try:
        # Determine the user's role and adjust the query accordingly
        if current_user.has_role("Admin"):
            if search_query:
                devices_query = DeviceManager.query.filter(
                    DeviceManager.device_name.ilike(f"%{search_query}%")
                    | DeviceManager.ip_address.ilike(f"%{search_query}%")
                    | DeviceManager.vendor.ilike(f"%{search_query}%")
                    | DeviceManager.description.ilike(f"%{search_query}%")
                    | DeviceManager.created_by.ilike(f"%{search_query}%")
                )
            else:
                devices_query = DeviceManager.query
        else:
            if search_query:
                devices_query = DeviceManager.query.filter(
                    DeviceManager.user_id == current_user.id,
                    (
                        DeviceManager.device_name.ilike(f"%{search_query}%")
                        | DeviceManager.ip_address.ilike(f"%{search_query}%")
                        | DeviceManager.vendor.ilike(f"%{search_query}%")
                        | DeviceManager.description.ilike(f"%{search_query}%")
                        | DeviceManager.created_by.ilike(f"%{search_query}%")
                    ),
                )
            else:
                devices_query = DeviceManager.query.filter_by(user_id=current_user.id)

        total_devices = devices_query.count()
        devices = devices_query.limit(per_page).offset(offset).all()
        pagination = Pagination(page=page, per_page=per_page, total=total_devices)

        return render_template(
            "/device_managers/index.html",
            form=form,
            page=page,
            per_page=per_page,
            search_query=search_query,
            total_devices=total_devices,
            devices=devices,
            pagination=pagination,
        )

    except Exception as e:
        # Handle exceptions and log the error
        current_app.logger.error(
            f"Error accessing Device Manager page by user {current_user.email}: {str(e)}"
        )
        flash(
            "An error occurred while accessing the Device Manager. Please try again later.",
            "danger",
        )
        return redirect(
            url_for("users.dashboard")
        )  # Redirect to a safe page like dashboard


@dm_bp.route("/create-device", methods=["GET", "POST"])
@login_required  # Ensure the user is logged in
@required_2fa  # Require two-factor authentication for added security
@role_required(
    roles=["Admin", "User"],  # Restrict access to Admin and User roles
    permissions=["Manage Devices"],  # Require 'Manage Devices' permission
    page="Devices Management",  # Indicate the page for role management
)
def create_device():
    """Add a new device to the database"""
    form = DeviceForm(request.form)  # Initialize the device form with request data

    if request.method == "POST":
        if form.validate_on_submit():
            try:
                # Check if a device with the same IP address or device name already exists
                exist_address = DeviceManager.query.filter_by(
                    ip_address=form.ip_address.data
                ).first()
                exist_device = DeviceManager.query.filter_by(
                    device_name=form.device_name.data
                ).first()

                if exist_device or exist_address:
                    # Provide feedback to the user if the device already exists
                    flash("Perangkat sudah terdaftar!", "info")
                    current_app.logger.info(
                        f"Duplicate device attempt: {form.device_name.data} or {form.ip_address.data} by {current_user.email}"
                    )
                else:
                    # Create a new device with the provided form data
                    new_device = DeviceManager(
                        device_name=form.device_name.data.strip(),
                        vendor=form.vendor.data.strip(),
                        ip_address=form.ip_address.data.strip(),
                        username=form.username.data.strip(),
                        password=form.password.data.strip(),
                        ssh=form.ssh.data.strip(),
                        description=form.description.data.strip(),
                        created_by=current_user.email,
                        user_id=current_user.id,
                    )
                    db.session.add(new_device)  # Add the new device to the session
                    db.session.commit()  # Commit the transaction to the database

                    # Provide success feedback to the user
                    flash("Perangkat berhasil ditambahkan!", "success")
                    current_app.logger.info(
                        f"Device created: {form.device_name.data.strip()} with IP {form.ip_address.data.strip()} by {current_user.email}"
                    )
                    return redirect(
                        url_for("dm.index")
                    )  # Redirect to the device management page
            except Exception as e:
                # Log the error and provide error feedback to the user
                current_app.logger.error(
                    f"Error creating device {form.device_name.data.strip()}: {str(e)}"
                )
                flash(
                    "Terjadi kesalahan saat membuat perangkat. Silakan coba lagi.",
                    "danger",
                )
                db.session.rollback()  # Rollback the transaction in case of error
        else:
            # Log each validation error and provide feedback to the user
            for field, errors in form.errors.items():
                for error in errors:
                    flash(

src/templates/device_managers/index.html
{% extends "/layouts/layout_table.html" %}
{% block page_heading %}Devices Management{% endblock %}
{% block title %}Devices Management{% endblock %}

{% block button_group1 %}
<!-- Tombol untuk membuka modal pembuatan perangkat baru -->
<button type="button" class="btn btn-sm btn-primary" data-bs-toggle="modal" data-bs-target="#createdeviceModal">
    Create New
</button>
{% endblock %}

{% block table_name %}Daftar Perangkat{% endblock %}

{% block form_filter_row %}
<form id="perPageForm" action="{{ url_for('dm.index') }}" method="get">
    <label class="d-flex align-items-center">
        <span>Tampilkan</span>
        <select name="per_page" class="form-select form-select-sm mx-2"
            onchange="document.getElementById('perPageForm').submit()">
            <option value="10" {% if per_page==10 %}selected{% endif %}>10</option>
            <option value="25" {% if per_page==25 %}selected{% endif %}>25</option>
            <option value="50" {% if per_page==50 %}selected{% endif %}>50</option>
        </select>
        <span>entri</span>
    </label>
    <input type="hidden" name="search" value="{{ search_query }}">
</form>
{% endblock %}

{% block form_search %}
<form id="searchForm" method="get" action="{{ url_for('dm.index') }}" class="form-inline d-flex">
    <input id="searchInput" type="text" name="search" class="form-control form-control-sm me-2"
        placeholder="Search..." value="{{ search_query }}">
    <button class="btn btn-outline-success btn-sm" type="submit">
        <i class="fas fa-search"></i>
    </button>
    <input type="hidden" name="per_page" value="{{ per_page }}">
</form>
{% endblock %}

{% block table_header %}
<th>No</th>
<th onclick="sortTable(0)">Nama Perangkat <i class="fas fa-sort"></i></th>
<th onclick="sortTable(1)">Vendor <i class="fas fa-sort"></i></th>
<th onclick="sortTable(2)">IP Address <i class="fas fa-sort"></i></th>
<th onclick="sortTable(3)">Username <i class="fas fa-sort"></i></th>
<th onclick="sortTable(4)">Password <i class="fas fa-sort"></i></th>
<th onclick="sortTable(5)">Port SSH <i class="fas fa-sort"></i></th>
<th>Aksi</th>
{% endblock %}

{% block table_body %}
{% for data in devices %}
<tr>
    <th scope="row">{{ loop.index + (page - 1) * per_page }}</th>
    <td>{{ data.device_name }}</td>
    <td>{{ data.vendor }}</td>
    <td>{{ data.ip_address }}</td>
    <td>{{ data.username }}</td>
    <td>
        <div class="d-flex align-items-center">
            <span class="password-display">{{ data.password | mask_password }}</span>
        </div>
    </td>
    <td>{{ data.ssh }}</td>
    <td>
        <button class="btn btn-info btn-sm mb-1" data-bs-toggle="modal" data-bs-target="#detailModal{{ data.id }}">
            <i class="fas fa-eye"></i>
        </button>
        <a href="{{ url_for('dm.update_device', device_id=data.id) }}" class="btn btn-success btn-sm mb-1">
            <i class="fas fa-edit"></i>
        </a>
        <form action="{{ url_for('dm.delete_device', device_id=data.id) }}" method="post" style="display:inline;">
            {{ form.csrf_token }} <!-- Adding CSRF token -->
            <button type="submit" class="btn btn-danger btn-sm mb-1"
                onclick="return confirm('Apakah Anda yakin ingin menghapus ?');">
                <i class="fas fa-trash"></i>
            </button>
        </form>
    </td>
</tr>

<!-- Modal Detail Perangkat -->
<div class="modal fade" id="detailModal{{ data.id }}" tabindex="-1" aria-labelledby="detailModalLabel{{ data.id }}"
    aria-hidden="true">
    <div class="modal-dialog modal-md">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="detailModalLabel{{ data.id }}">Detail Perangkat</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p><strong>Nama Perangkat:</strong> {{ data.device_name }}</p>
                <p><strong>Vendor:</strong> {{ data.vendor }}</p>
                <p><strong>IP Address:</strong> {{ data.ip_address }}</p>
                <p><strong>Username:</strong> {{ data.username }}</p>
                <p><strong>Password:</strong> {{ data.password }}</p>
                <p><strong>Port SSH:</strong> {{ data.ssh }}</p>
                <p><strong>Description:</strong> {{ data.description }}</p>
                <p><strong>Dibuat oleh:</strong> {{ data.created_by }}</p>
                <p><strong>Status Jaringan:</strong> {{ data.status }}</p>
            </div>
        </div>
    </div>
</div>

{% endfor %}
{% endblock %}

{% block show_total_data %}
<div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">
    Menampilkan {{ (page - 1) * per_page + 1 }} hingga {{ (page - 1) * per_page + per_page if
    (page - 1)
    * per_page + per_page < total_devices else total_devices }} dari {{ total_devices }} entri </div>

{% endblock %}

{% block pagination %}
    {{ pagination.links }}

{% endblock %}

{% block modal_data %}
<!-- create device Modal -->
<div class="modal fade" id="createdeviceModal" tabindex="-1" aria-labelledby="createdeviceModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" style="max-width: 500px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createdeviceModalLabel">Buat Perangkat Baru</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{ url_for('dm.create_device') }}">
                    {{ form.hidden_tag() }} <!-- Adding CSRF token -->

                    <div class="mb-3">
                        {{ form.device_name.label(class_="form-label") }}
                        {{ form.device_name(class_="form-control") }}
                        {% if form.device_name.errors %}
                        <div class="text-danger">
                            {% for error in form.device_name.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ form.vendor.label(class_="form-label") }}
                        {{ form.vendor(class_="form-control") }}
                        {% if form.vendor.errors %}
                        <div class="text-danger">
                            {% for error in form.vendor.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ form.ip_address.label(class_="form-label") }}
                        {{ form.ip_address(class_="form-control") }}
                        {% if form.ip_address.errors %}
                        <div class="text-danger">
                            {% for error in form.ip_address.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ form.username.label(class_="form-label") }}
                        {{ form.username(class_="form-control") }}
                        {% if form.username.errors %}
                        <div class="text-danger">
                            {% for error in form.username.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ form.password.label(class_="form-label") }}
                        {{ form.password(class_="form-control") }}
                        {% if form.password.errors %}
                        <div class="text-danger">
                            {% for error in form.password.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ form.ssh.label(class_="form-label") }}
                        {{ form.ssh(class_="form-control") }}
                        {% if form.ssh.errors %}
                        <div class="text-danger">
                            {% for error in form.ssh.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <div class="mb-3">
                        {{ form.description.label(class_="form-label") }}
                        {{ form.description(class_="form-control") }}
                        {% if form.description.errors %}
                        <div class="text-danger">
                            {% for error in form.description.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>

                    <button type="submit" class="btn btn-sm btn-primary">
                        <i class="fas fa-plus"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script_js %}
<script>
    let timeout = null;

    document.getElementById("searchInput").addEventListener("input", function () {
        clearTimeout(timeout);

        timeout = setTimeout(function () {
            document.getElementById('searchForm').submit();
        }, 1000);
    });

    document.getElementById("searchInput").addEventListener("input", function () {
        const query = this.value.toLowerCase();
        const rows = document.querySelectorAll("#deviceTable tbody tr");

        rows.forEach(row => {
            const deviceName = row.cells[2].textContent.toLowerCase();
            const ipAddress = row.cells[3].textContent.toLowerCase();
            const vendor = row.cells[4].textContent.toLowerCase();

            if (
                deviceName.includes(query) ||
                ipAddress.includes(query) ||
                vendor.includes(query)
            ) {
                row.style.display = "";
            } else {
                row.style.display = "none";
            }
        });
    });
</script>
{% endblock %}

src/templates/device_managers/update_device.html
{% extends "/layouts/layout.html" %}
{% block title %}Update Device - {{form.device_name.data}} {% endblock %}
{% block content %}
<div class="card position-relative py-4 px-4">
    <div class="card-header mb-3">
        Update Device
    </div>
    <form action="{{ url_for('dm.update_device', device_id=device.id) }}" method="POST">
        {{ form.csrf_token }} <!-- Adding CSRF token -->
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.device_name.label(class_="form-label") }}
                {{ form.device_name(class_="form-control") }}
            </div>
            <div class="col-md-6">
                {{ form.vendor.label(class_="form-label") }}
                {{ form.vendor(class_="form-control") }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.ip_address.label(class_="form-label") }}
                {{ form.ip_address(class_="form-control") }}
            </div>
            <div class="col-md-6">
                {{ form.username.label(class_="form-label") }}
                {{ form.username(class_="form-control") }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-6">
                {{ form.password.label(class_="form-label") }}
                <div class="input-group">
                    {{ form.password(class_="form-control", id="password") }}
                    <span class="input-group-text">
                        <i class="fa-solid fa-eye" id="togglePassword" style="cursor: pointer;"></i>
                    </span>
                </div>
                <small class="form-text text-muted">Leave empty to keep the current password</small>
            </div>
            <div class="col-md-6">
                {{ form.ssh.label(class_="form-label") }}
                {{ form.ssh(class_="form-control") }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-12">
                {{ form.description.label(class_="form-label") }}
                {{ form.description(class_="form-control") }}
            </div>
        </div>

        <!-- Tombol Aksi -->
        <button type="submit" class="btn btn-sm btn-success">
            <i class="fa-solid fa-check"></i> Save Changes
        </button>
        <a class="btn btn-sm btn-warning" href="{{ url_for('dm.index') }}">
            <i class="fa-solid fa-arrow-left"></i> Back
        </a>
    </form>
</div>

<script>
    document.getElementById('togglePassword').addEventListener('click', function () {
        var passwordField = document.getElementById('password');
        if (passwordField.type === 'password') {
            passwordField.type = 'text';
        } else {
            passwordField.type = 'password';
        }
    });
</script>

{% endblock %}