src/__init__.py
from decouple import config as decouple_config
from flask import Flask, Response
import logging
from logging import StreamHandler
from flask_wtf.csrf import CSRFProtect
from flask_bcrypt import Bcrypt
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from dotenv import load_dotenv
from src.utils.is_active_utils import is_active
from src.utils.mask_password_utils import mask_password
from src.config import DevelopmentConfig, TestingConfig, ProductionConfig, get_uuid_type
from flask_mail import Mail
from flask_talisman import Talisman
import openai
import os
from flask_marshmallow import Marshmallow
from flask_jwt_extended import JWTManager

# Load .env file variable
load_dotenv()

# Initialize extensions
bcrypt = Bcrypt()
db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()
csrf = CSRFProtect()
mail = Mail()
ma = Marshmallow()
jwt = JWTManager()

# Global variable for UUID type
UUID_TYPE = None


def create_app(config_class=None):
    global UUID_TYPE

    app = Flask(__name__)

    # Membaca konfigurasi dari file .env
    config_name = decouple_config("CONFIG_NAME", default="Development")

    # Memilih konfigurasi berdasarkan nama
    if config_name == "Development":
        app.config.from_object(DevelopmentConfig)
    elif config_name == "Testing":
        app.config.from_object(TestingConfig)
    elif config_name == "Production":
        app.config.from_object(ProductionConfig)
    else:
        raise ValueError("Invalid CONFIG_NAME")

    # Pastikan semua direktori yang dibutuhkan ada
    for directory in [
        app.config["BACKUP_DIR"],
        app.config["CONFIG_DIR"],
        app.config["TEMPLATE_DIR"],
    ]:
        try:
            if not os.path.exists(directory):
                os.makedirs(directory)
                app.logger.info(f"Created missing directory: {directory}")
            else:
                app.logger.info(f"Directory already exists: {directory}")
        except OSError as e:
            app.logger.error(f"Error creating directory {directory}: {e}")
            raise RuntimeError(f"Failed to create directory: {directory}")

    # Inisiasi pustaka OpenAI dengan API key
    openai_api_key = decouple_config("OPENAI_API_KEY", default=None)
    talita_api_key = decouple_config("TALITA_API_KEY", default=None)
    talita_url = decouple_config("TALITA_URL", default=None)

    # JWT Secret Key
    jwt_secret_key = decouple_config("JWT_SECRET_KEY", default=None)

    # Pengecekan apakah variabel konfigurasi penting telah dimuat
    if not openai_api_key:
        raise ValueError("Missing required configuration: OPENAI_API_KEY")
    if not talita_api_key:
        raise ValueError("Missing required configuration: TALITA_API_KEY")
    if not talita_url:
        raise ValueError("Missing required configuration: TALITA_URL")

    # Set API key untuk OpenAI
    openai.api_key = openai_api_key

    # Simpan TALITA API Key dan URL ke dalam konfigurasi aplikasi
    app.config["TALITA_API_KEY"] = talita_api_key
    app.config["TALITA_URL"] = talita_url

    # set config for JWT Extended Library
    app.config["JWT_SECRET_KEY"] = jwt_secret_key
    app.config["JWT_ACCESS_TOKEN_EXPIRES"] = (
        False  # Token akses tidak pernah kedaluwarsa
    )
    app.config["JWT_REFRESH_TOKEN_EXPIRES"] = (
        False  # Token refresh juga tidak pernah kedaluwarsa
    )

    # Initialize extensions
    bcrypt.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    csrf.init_app(app)
    mail.init_app(app)
    ma.init_app(app)
    jwt.init_app(app)
    talisman = Talisman(
        app,
        force_https=app.config["TALISMAN_FORCE_HTTPS"],
        strict_transport_security=app.config["TALISMAN_STRICT_TRANSPORT_SECURITY"],
        strict_transport_security_max_age=app.config[
            "TALISMAN_STRICT_TRANSPORT_SECURITY_MAX_AGE"
        ],
        content_security_policy=app.config["TALISMAN_CONTENT_SECURITY_POLICY"],
    )

    # Set UUID type based on database type
    UUID_TYPE = get_uuid_type(app.config["SQLALCHEMY_DATABASE_URI"])

    # Konfigurasi logger
    handler = StreamHandler()
    handler.setLevel(logging.INFO)
    formatter = logging.Formatter(
        "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    handler.setFormatter(formatter)

    app.logger.addHandler(handler)
    app.logger.setLevel(logging.INFO)

    # Register context processor
    app.jinja_env.filters["mask_password"] = mask_password

    # Middleware to modify the Server header
    @app.after_request
    def hide_server_header(response: Response):
        # Change the Server header or remove it completely
        response.headers["Server"] = "Hidden Server"
        return response

    @app.context_processor
    def utility_processor():
        return dict(is_active=is_active)

    # Register blueprints
    from .controllers.main_controller import main_bp
    from .controllers.users_controller import users_bp
    from .controllers.profile_controller import profile_bp
    from .controllers.roles_controller import roles_bp
    from .controllers.device_manager_controller import dm_bp
    from .controllers.template_manager_controller import tm_bp
    from .controllers.config_manager_controller import nm_bp
    from .utils.error_helper_utils import error_bp
    from .controllers.backup_controller import backup_bp
    from .controllers.ai_chatbot_controller import chatbot_bp
    from .controllers.config_file_manager_controller import config_file_bp
    from .controllers.restfull_api_controller import restapi_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(users_bp)
    app.register_blueprint(profile_bp)
    app.register_blueprint(roles_bp)
    app.register_blueprint(dm_bp)
    app.register_blueprint(tm_bp)
    app.register_blueprint(nm_bp)
    app.register_blueprint(error_bp)
    app.register_blueprint(backup_bp)
    app.register_blueprint(chatbot_bp)
    app.register_blueprint(config_file_bp)
    app.register_blueprint(restapi_bp)

    # Set up user loader
    from .models.app_models import User

    login_manager.login_view = "main.login"

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.filter(User.id == user_id).first()

    return app

src/controllers/roles_controller.py
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    jsonify,
    current_app,
)
from flask_login import login_required, current_user, logout_user
from flask_paginate import Pagination, get_page_args
from src import db
from src.models.app_models import User, Role, Permission, UserRoles
from .decorators import role_required, login_required, required_2fa
import logging

# Membuat blueprint roles_bp dan error_bp
roles_bp = Blueprint("roles", __name__)
error_bp = Blueprint("error", __name__)

# Setup logging untuk aplikasi
logging.basicConfig(level=logging.INFO)


@roles_bp.before_app_request
def setup_logging():
    """
    Mengatur level logging untuk aplikasi.
    """
    current_app.logger.setLevel(logging.INFO)
    handler = current_app.logger.handlers[0]
    current_app.logger.addHandler(handler)


@error_bp.app_errorhandler(404)
def page_not_found(error):
    """
    Menangani error 404 dan menampilkan halaman 404.
    """
    current_app.logger.error(f"Error 404: {error}")
    return render_template("main/404.html"), 404


# Middleware untuk autentikasi dan otorisasi sebelum permintaan.
@roles_bp.before_request
def before_request_func():
    """
    Memeriksa apakah pengguna telah terotentikasi sebelum setiap permintaan.
    Jika pengguna harus logout paksa, lakukan logout dan arahkan ke halaman login.
    Jika tidak terotentikasi, kembalikan pesan 'Unauthorized access'.
    """
    if not current_user.is_authenticated:
        current_app.logger.warning(
            f"Unauthorized access attempt by {request.remote_addr}"
        )
        return render_template("main/404.html"), 404

    # Jika pengguna terotentikasi dan memiliki flag force_logout, lakukan logout
    if current_user.force_logout:
        current_user.force_logout = False  # Reset the flag
        db.session.commit()
        logout_user()
        flash("Your password has been updated. Please log in again.", "info")
        return redirect(url_for("main.login"))


@roles_bp.context_processor
def inject_user():
    """
    Menyediakan first_name dan last_name pengguna yang terotentikasi ke dalam template.
    """
    if current_user.is_authenticated:
        return dict(
            first_name=current_user.first_name, last_name=current_user.last_name
        )
    return dict(first_name="", last_name="")


# --------------------------------------------------------------------------------
# Roles Management Section
# --------------------------------------------------------------------------------


# Halaman Roles
@roles_bp.route("/roles-management", methods=["GET", "POST"])
@login_required
@required_2fa
@role_required(roles=["Admin"], permissions=["Manage Roles"], page="Roles Management")
def index():
    """Menampilkan halaman utama untuk mengelola role dan pengguna."""
    current_app.logger.info(
        f"User {current_user.email} accessed Roles Management page."
    )

    try:
        all_roles = Role.query.all()  # Mengambil semua role
        all_users = User.query.all()  # Mengambil semua pengguna

        search_query = request.args.get(
            "search", ""
        ).lower()  # Mengambil query pencarian
        page, per_page, offset = get_page_args(
            page_parameter="page", per_page_parameter="per_page", per_page=10
        )

        # Menerapkan filter pencarian jika ada
        role_query = (
            Role.query.filter(Role.name.ilike(f"%{search_query}%"))
            if search_query
            else Role.query
        )
        total_roles = role_query.count()  # Menghitung total role yang sesuai
        roles = (
            role_query.limit(per_page).offset(offset).all()
        )  # Mengambil role untuk halaman ini

        pagination = Pagination(
            page=page,
            per_page=per_page,
            total=total_roles,
        )

        return render_template(
            "/role_management/index.html",
            roles=roles,
            page=page,
            per_page=per_page,
            pagination=pagination,
            search_query=search_query,
            total_roles=total_roles,
            all_roles=all_roles,
            all_users=all_users,
        )

    except Exception as e:
        current_app.logger.error(f"Error occurred in Roles Management: {str(e)}")
        flash(
            "Terjadi kesalahan saat memuat halaman Role Management. Silakan coba lagi.",
            "danger",
        )
        return redirect(url_for("users.dashboard"))


# Membuat Role Baru dengan Modal
@roles_bp.route("/create-role", methods=["POST"])
@login_required
@required_2fa
@role_required(roles=["Admin"], permissions=["Manage Roles"], page="Roles Management")
def create_role():
    """Membuat role baru dan menyimpannya ke dalam database."""
    current_app.logger.info(f"User {current_user.email} accessed Create Role page.")

    role_name = request.form.get("name")
    role_permissions = request.form.getlist("permissions")

    # Validasi input
    if not role_name or not role_permissions:
        current_app.logger.warning(
            f"User {current_user.email} gagal membuat role baru: nama atau permissions kosong."
        )
        flash("Nama role dan permissions tidak boleh kosong!", "warning")
        return redirect(url_for("roles.index"))

    try:
        # Check if role already exists
        if Role.query.filter_by(name=role_name).first():
            current_app.logger.warning(
                f"User {current_user.email} gagal membuat role baru: role '{role_name}' sudah ada."
            )
            flash("Role sudah ada!", "error")
            return redirect(url_for("roles.index"))

        # Create new role with permissions
        new_role = Role(
            name=role_name,
            permissions=[Permission.query.get(p) for p in role_permissions],
        )
        db.session.add(new_role)
        db.session.commit()

        current_app.logger.info(
            f"User {current_user.email} berhasil membuat role baru: {role_name}."
        )
        flash("Role berhasil ditambah!", "success")
        return redirect(url_for("roles.index"))

    except Exception as e:
        current_app.logger.error(
            f"Error creating role '{role_name}' by user {current_user.email}: {str(e)}"
        )
        flash("Terjadi kesalahan saat membuat role baru. Silakan coba lagi.", "danger")
        db.session.rollback()
        return redirect(url_for("roles.index"))


# Memperbarui Role
@roles_bp.route("/update-role/<role_id>", methods=["GET", "POST"])
@login_required
@required_2fa
@role_required(roles=["Admin"], permissions=["Manage Roles"], page="Roles Management")
def update_role(role_id):
    """Memperbarui role yang ada berdasarkan ID."""
    current_app.logger.info(
        f"User {current_user.email} is accessing update role for role ID {role_id}."
    )

    role = Role.query.get_or_404(role_id)  # Mengambil role berdasarkan ID

    if request.method == "POST":
        role_name = request.form.get("name")
        selected_permissions = request.form.getlist("permissions")
        selected_users = request.form.getlist("users")

        if not role_name:
            current_app.logger.warning(
                f"User {current_user.email} gagal memperbarui role {role.name} karena nama role kosong."
            )
            flash("Nama role tidak boleh kosong!", "warning")
            return redirect(url_for("roles.update_role", role_id=role_id))

        if Role.query.filter(Role.id != role.id, Role.name == role_name).first():
            current_app.logger.warning(
                f"User {current_user.email} gagal memperbarui role {role.name} karena role dengan nama tersebut sudah ada."
            )
            flash("Role dengan nama tersebut sudah ada!", "error")
            return redirect(url_for("roles.update_role", role_id=role_id))

        try:
            role.name = role_name

            # Memperbarui asosiasi permissions
            role.permissions = [
                Permission.query.get(permission_id)
                for permission_id in selected_permissions
            ]

            # Memperbarui asosiasi pengguna
            role.users = [User.query.get(user_id) for user_id in selected_users]

            db.session.commit()
            current_app.logger.info(
                f"User {current_user.email} berhasil memperbarui role {role.name}."
            )
            flash("Role berhasil diubah.", "success")
            return redirect(url_for("roles.index"))

        except Exception as e:
            db.session.rollback()
            current_app.logger.error(
                f"Error updating role '{role.name}' by user {current_user.email}: {str(e)}"
            )
            flash(
                "Terjadi kesalahan saat memperbarui role. Silakan coba lagi.", "danger"
            )
            return redirect(url_for("roles.update_role", role_id=role_id))

    # Mengambil pengguna terkait dan semua permissions
    associated_users = (
        User.query.join(UserRoles).filter(UserRoles.role_id == role_id).all()
    )
    all_permissions = Permission.query.all()

    # Mengambil permissions yang terkait dengan role ini
    associated_permissions = {permission.id for permission in role.permissions}

    return render_template(
        "/role_management/update_role.html",
        role=role,
        associated_users=associated_users,
        all_permissions=all_permissions,
        associated_permissions=associated_permissions,
    )


# Menghapus Role
@roles_bp.route("/delete-role/<role_id>", methods=["POST"])
@login_required
@required_2fa
@role_required(roles=["Admin"], permissions=["Manage Roles"], page="Roles Management")
def delete_role(role_id):
    """Menghapus role dari database jika tidak ada asosiasi pengguna atau permissions."""
    current_app.logger.info(
        f"User {current_user.email} is attempting to delete role with ID {role_id}."
    )

src/templates/role_management/index.html
{% extends "/layouts/layout_table.html" %}
{% block page_heading %}Roles Management{% endblock %}
{% block title %}Roles Management{% endblock %}

{% block button_group1 %}
<!-- Tombol tambah role -->
<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#rolecreateModal">
    Create role
</button>
{% endblock %}

{% block button_group2 %}
<!-- Tombol tambah permission -->
<button class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#addUserToRoleModal">
    Assign role user
</button>
{% endblock %}


<!-- Data Table Start -->
{% block table_name %}Roles Management{% endblock %}

{% block form_filter_row %}
<form id="perPageForm" action="{{ url_for('roles.index') }}" method="get">
    <label class="d-flex align-items-center">
        <span>Tampilkan</span>
        <select name="per_page" class="form-select form-select-sm mx-2"
            onchange="document.getElementById('perPageForm').submit()">
            <option value="10" {% if per_page==10 %}selected{% endif %}>10</option>
            <option value="25" {% if per_page==25 %}selected{% endif %}>25</option>
            <option value="50" {% if per_page==50 %}selected{% endif %}>50</option>
        </select>
        <span>entri</span>
    </label>
    <input type="hidden" name="search" value="{{ search_query }}">
</form>
{% endblock %}

{% block form_search %}
<form id="searchForm" method="get" action="{{ url_for('roles.index') }}" class="form-inline d-flex">
    <input id="searchInput" type="text" name="search" class="form-control form-control-sm mr-2" placeholder="Search..."
        value="{{ search_query }}">
    <button class="btn btn-outline-success btn-sm" type="submit">
        <i class="fa-solid fa-magnifying-glass"></i>
    </button>
    <input type="hidden" name="per_page" value="{{ per_page }}">
</form>
{% endblock %}

{% block table_header %}
<th>ID</th>
<th onclick="sortTable(0)">Nama Role <i class="fas fa-sort"></i></th>
<th>Permissions</th>
<th>Aksi</th>
{% endblock %}

{% block table_body %}
{% for role in roles %}
<tr>
    <th scope="row">{{ loop.index + (page - 1) * per_page }}</th>
    <td>{{ role.name }}</td>
    <td>
        {% for permission in role.permissions %}
        <span class="badge bg-primary">{{ permission.name }}</span>
        {% endfor %}
    </td>
    <td>
        <!-- Tombol untuk Melihat Detail -->
        <button class="btn btn-info btn-sm mb-1" data-bs-toggle="modal" data-bs-target="#detailModal{{ role.id }}">
            <i class="fas fa-eye"></i>
        </button>

        <!-- Tombol untuk Update -->
        <a href="{{ url_for('roles.update_role', role_id=role.id) }}" class="btn btn-success btn-sm mb-1">
            <i class="fa-solid fa-edit"></i>
        </a>

        <!-- Tombol untuk Delete -->
        <form method="post" action="{{ url_for('roles.delete_role', role_id=role.id) }}" class="d-inline"
            onsubmit="return confirm('Anda yakin ingin menghapus role ini?');">
            <button type="submit" class="btn btn-danger btn-sm mb-1">
                <i class="fa-solid fa-trash"></i>
            </button>
        </form>
    </td>
</tr>

<!-- Modal Detail Role -->
<div class="modal fade" id="detailModal{{ role.id }}" tabindex="-1" aria-labelledby="detailModalLabel{{ role.id }}"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-black">
            <div class="modal-header">
                <h5 class="modal-title" id="detailModalLabel{{ role.id }}">
                    Detail Role</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p><strong>Nama role:</strong> {{ role.name }}</p>
                <p>
                    <strong>
                        User terasosiasi:
                    </strong>
                    {% for user in role.users %}
                    <span class="badge bg-success">{{ user.email }}</span>
                    {% endfor %}
                </p>
                <p>
                    <strong>
                        Permissions:
                    </strong>
                    {% for permission in role.permissions %}
                    <span class="badge bg-primary">{{ permission.name }}</span>
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

{% block show_total_data %}
<div class="dataTables_info" id="dataTable_info" role="status" aria-live="polite">
    Menampilkan {{ (page - 1) * per_page + 1 }} hingga {{ (page - 1) * per_page + per_page if
    (page - 1) * per_page + per_page < total_roles else total_roles }} dari {{ total_roles }} entri </div>

        {% endblock %}

        {% block pagination %}
        <!-- Link Pagination -->
        {{ pagination.links }}
        {% endblock %}

        {% block modal_data %}
        <!-- Create Role Modal -->
        <div class="modal fade" id="rolecreateModal" tabindex="-1" aria-labelledby="rolecreateModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content bg-black text-light">
                    <div class="modal-header">
                        <h5 class="modal-title" id="rolecreateModalLabel">Tambah Role Baru</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{{ url_for('roles.create_role') }}">
                            <div class="mb-3">
                                <label for="name" class="form-label">Nama Role</label>
                                <input type="text" class="form-control" id="name" name="name" required>
                            </div>
                            <div class="mb-3">
                                <label class="form-label">Permissions</label>
                                <div id="permissionsContainer" class="row">
                                    <!-- Permissions will be dynamically added here -->
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Create</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <!-- Modal Tambah User ke Role -->
        <div class="modal fade" id="addUserToRoleModal" tabindex="-1" aria-labelledby="addUserToRoleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content bg-black text-white">
                    <div class="modal-header">
                        <h5 class="modal-title" id="addUserToRoleModalLabel">Tambah User ke Role</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button>
                    </div>
                    <div class="modal-body">
                        <form method="post" action="{{ url_for('roles.add_user_to_role') }}">
                            <div class="form-group">
                                <label for="user_id">Pilih User</label>
                                <select class="form-control" id="user_id" name="user_id">
                                    {% for user in all_users %}
                                    <option value="{{ user.id }}">{{ user.email }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group mt-3">
                                <label for="role_name">Pilih Role</label>
                                <select class="form-control" id="role_name" name="role_name">
                                    {% for role in all_roles %}
                                    <option value="{{ role.name }}">{{ role.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">Tambah</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}

        {% block script_js %}
        <script>
            let timeout = null;

            // Menangani input pada form pencarian dengan penundaan 1 detik
            document.getElementById("searchInput").addEventListener("input", function () {
                // Batalkan timer yang ada sebelumnya jika ada
                clearTimeout(timeout);

                // Setel timer baru untuk submit form setelah 1 detik
                timeout = setTimeout(function () {
                    document.getElementById('searchForm').submit();
                }, 1000); // 1000 ms = 1 detik
            });

            // fungsi untuk load data permissions di dalam modal tambah role
            document.addEventListener('DOMContentLoaded', function () {
                var roleCreateModal = document.getElementById('rolecreateModal');

                roleCreateModal.addEventListener('show.bs.modal', function () {
                    fetch('/api/permissions')
                        .then(response => response.json())
                        .then(data => {
                            var permissionsContainer = document.getElementById('permissionsContainer');
                            permissionsContainer.innerHTML = '';

                            data.forEach(permission => {
                                var permissionElement = document.createElement('div');
                                permissionElement.classList.add('col-12', 'mb-2');
                                permissionElement.innerHTML = `
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="${permission.id}" id="permission_${permission.id}" name="permissions">
                                <label class="form-check-label" for="permission_${permission.id}">
                                    <span class="badge bg-primary">${permission.name}</span>
                                </label>
                            </div>
                        `;
                                permissionsContainer.appendChild(permissionElement);
                            });
                        })
                        .catch(error => console.error('Error loading permissions:', error));
                });
            });

        </script>
        {% endblock %}

src/templates/role_management/index_permissions.html
{% extends "/layouts/layout_table.html" %}
{% block page_heading %}User Permissions{% endblock %}
{% block title %}Permissions Management{% endblock %}


{% block button_group1 %}
<!-- Tombol untuk menampilkan modal Create Permission -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createPermissionModal">
    Create new
</button>
{% endblock %}


<!-- Data Table Start -->
{% block table_name %}Permissions Management{% endblock %}

{% block table_header %}
<th>No</th>
<th onclick="sortTable(0)">Nama <i class="fas fa-sort"></i></th>
<th onclick="sortTable(1)">Deskripsi <i class="fas fa-sort"></i></th>
<th onclick="sortTable(2)">Aksi <i class="fas fa-sort"></i></th>
{% endblock %}

{% block table_body %}
{% for permission in permissions %}
<tr>
    <th scope="row">{{ loop.index }}</th>
    <td>{{ permission.name }}</td>
    <td>{{ permission.description }}</td>
    <td>
        <!-- Tombol untuk menampilkan modal Update Permission -->
        <button class="btn btn-success btn-sm mb-1" data-bs-toggle="modal"
            data-bs-target="#updatePermissionModal{{ permission.id }}">
            <i class="fas fa-edit"></i>
        </button>

        <!-- Form untuk Menghapus Permission -->
        <form action="{{ url_for('roles.delete_permission', permission_id=permission.id) }}" method="post"
            style="display:inline;">
            <button type="submit" class="btn btn-danger btn-sm mb-1"
                onclick="return confirm('Apakah Anda yakin ingin menghapus permission ini?');">
                <i class="fas fa-trash"></i>
            </button>
        </form>
    </td>
</tr>

<!-- Modal Update Permission -->
<div class="modal fade" id="updatePermissionModal{{ permission.id }}" tabindex="-1"
    aria-labelledby="updatePermissionModalLabel{{ permission.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-black text-white">
            <div class="modal-header">
                <h5 class="modal-title" id="updatePermissionModalLabel{{ permission.id }}">Update
                    Permission</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{ url_for('roles.update_permission', permission_id=permission.id) }}">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nama Permission</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ permission.name }}"
                            required>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Deskripsi</label>
                        <textarea class="form-control" id="description" name="description"
                            rows="3">{{ permission.description }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Update</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

{% block modal_data %}
<!-- Modal Create Permission -->
<div class="modal fade" id="createPermissionModal" tabindex="-1" aria-labelledby="createPermissionModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content bg-black text-white">
            <div class="modal-header">
                <h5 class="modal-title" id="createPermissionModalLabel">Tambah Permission Baru</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{ url_for('roles.create_permission') }}">
                    <div class="mb-3">
                        <label for="name" class="form-label">Nama Permission</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Deskripsi</label>
                        <textarea class="form-control" id="description" name="description" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Create</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}